package com.galaxyyao.springbootdroolstest1
import com.weds.drools.test.Message
dialect  "mvel"

rule "Hello World"
    dialect "mvel"
    when
        m : Message(status == Message.HELLO, message : message )
    then
        System.out.println( message);
    modify ( m ) { message = "Goodbye cruel world",status = Message.GOODBYE };
end

rule "Good Bye"
    dialect "java"
    when
        m:Message( status == Message.GOODBYE, message : message )
    then
        // m.setMessage("Goodbye cruel world");
        // update( m );
        System.out.println( message );
end